// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Breadcrumbs: typeof import('./components/navigation/breadcrumbs.vue')['default']
    BtnRoundedCircle: typeof import('./components/btn-rounded-circle.vue')['default']
    CardGateway: typeof import('./components/card/card-gateway.vue')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    DialogFindGateway: typeof import('./components/dialog/dialog-find-gateway.vue')['default']
    DomainDetailList: typeof import('./components/domain-detail-list.vue')['default']
    FormGateway: typeof import('./components/form/form-gateway.vue')['default']
    FormGatewayOld: typeof import('./components/form/form-gateway-old.vue')['default']
    GatewayBadge: typeof import('./components/gateway-badge.vue')['default']
    GatewayCredentials: typeof import('./components/gateway-credentials.vue')['default']
    NavSidebarLevelOne: typeof import('./components/navigation-v2/nav-sidebar-level-one.vue')['default']
    NavSidebarLevelTwo: typeof import('./components/navigation-v2/nav-sidebar-level-two.vue')['default']
    NavSidebarLevelTwoGateway: typeof import('./components/navigation-v2/nav-sidebar-level-two-gateway.vue')['default']
    NavTopbarDetails: typeof import('./components/navigation-v2/nav-topbar-details.vue')['default']
    NavTopbarGlobal: typeof import('./components/navigation-v2/nav-topbar-global.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SpotGatewayState: typeof import('./components/spot/spot-gateway-state.vue')['default']
  }
}
