// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Breadcrumbs: typeof import('./components/navigation/breadcrumbs.vue')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    FormGateway: typeof import('./components/form/form-gateway.vue')['default']
    GatewayCredentials: typeof import('./components/gateway-credentials.vue')['default']
    NavSidebar: typeof import('./components/navigation/nav-sidebar.vue')['default']
    NavTopbar: typeof import('./components/navigation/nav-topbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
